### ISSUE TITLE
Add notice that the command String for bot.on('command', (command, ...) is lowercase

### ISSUE THREAD

**Issue by CptPie** [NightfallAlicorn/telegram-bot-nova#2]
I wrote the function toggleDev which basically toggles the devMode on and off, while testing i was wondering why the command wouldn't trigger.

After playing around i found out by using the console log, that the command String is lowercase even if the Command is uppercase.

Command in Telegram: `/Foobar`
Console Log: ` foobar /Foobar`
Relevant Bot Code: 
```
bot.on('command', (chat, data, from, messageId, text, command, commandData) => {
	console.log(command+' '+text)
	if (command === 'start') {
		bot.sendText(chat.id, 'Hello world.')
		return
	}
	if (command === 'Foobar') {    //this will not turn true, even if the input is /Foobar
		console.log('foobar')
		return
	}
})
```
I was wondering why there was no notice that the command String is lowercase.

**Comment by NightfallAlicorn** [comment]
This is an error on my part. I've updated the README.md and npm package to clarify this for the developers. Thanks for informing me about it.

This is set to lowercase to help avoid commands failing due typing caps by mistake.

`command === 'start'` for example if a user types "/Start" it will still be able to trigger.

**Comment by CptPie** [comment]
Thank you for your work and fast response - i am closing this issue as it is resolved
