### ISSUE TITLE
on kick method get error

### ISSUE THREAD

**Issue by dilshads** [NightfallAlicorn/telegram-bot-nova#3]
code 

bot.on('command', (targetChat, userId, command, commandData) => {
  if (command === 'kick') {
    bot.kickChatMember(targetChat, userId)
    return
  }
}

Error: 
bot.kickChatMember(targetChat, userId, (error) => {
                   ^

ReferenceError: targetChat is not defined
    at Object.<anonymous> (/home/dilshad/telegram/MiFcDelhi.js:96:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by dilshads** [comment]
can you please share kick code ?

**Comment by NightfallAlicorn** [comment]
Here's working example I just made.

```js
'use strict'

const TelegramBot = require('telegram-bot-nova')

var bot = new TelegramBot(YOUR_BOT_TOKEN)

bot.on('replyCommand', (chat, date, from, messageId, text, command, commandData, target) => {
  // Type /kick while using reply on target user
  if (command === 'kick') {
    // Attempt to kick from the target chat the target user
    bot.kickChatMember(chat.id, target.id, (error) => {
      // If an occurs, send error message
      // Note that no error will be thrown if the target has already been removed
      if (error) {
        bot.sendText(chat.id, error.message)
        return
      }
      // If success, send message that the target user was kicked by the command user
      bot.sendText(chat.id, `${target.first_name} was kicked by ${from.first_name}`)
    })
    return
  }
})
```

Sadly, it isn't possible to `/kick User Name` since Telegram severs will only accept a user id as a target parameter. So using `replyCommand` will be the most reliable and easiest to use.

Good luck with your bot making.

**Comment by dilshads** [comment]
Thanks for reply its working :) 
Easy code

**Comment by dilshads** [comment]
warnChatMember (targetChat, userId, callback) {
    var urlQuery = { 'chat_id': targetChat, 'user_id': userId }

    web(this, 'warnChatMember', urlQuery, (data) => {
      if (typeof callback === 'function') {
        if (data.ok) {
          callback(null)
        } else {
          callback(new Error(data.description))
        }
      }
    })
  }

for warning i have to add this code on your main Nova bot file ?

then i can use this code

**Comment by NightfallAlicorn** [comment]
I don't think there's a `warnChatMember` method on Telegram servers. telegram-bot-nova acts as an easy interface. You'll have to code your method on how to handle on replyCommand by keeping track of the user's id.

**Comment by dilshads** [comment]
as i saw other group butler bot are able to store warning data and working fine

**Comment by dilshads** [comment]
Solution is this but not an easy solution 
1> Count the number of the messages that a user sends within a second which won't be so easy without having a database. But if you have a database with a table called Black_List and save all the messages with their sent-time in another table, you'll be able to count the number of messages sent via one specific ChatID in a pre-defined time period(In your case; 1 second) and check if the count is bigger than 5 or not, if the answer was YES you can insert that ChatID to the Black_List table.

2> Every time the bot receives a message it must run a database query to see that the sender's chatID exists in the Black_List table or not. If it exists it should continue its own job and ignore the message(Or even it can send an alert to the user saying: "You're blocked." which I think can be time consuming).

**Comment by dilshads** [comment]
@NightfallAlicorn can i use restrictChatMember method for the warn i mean can mute user for 5 mint any parametter to pass with /warn 
how can i pass that 5 mint time with it ?
bot.on('replyCommand', (chat, date, from, messageId, text, command, commandData, target) => {
  if (command === 'warn') {
    bot.restrictChatMember(chat.id, target.id, (error) => {
      if (error) {
        bot.sendText(chat.id, error.message)
        return
      }
      bot.sendText(chat.id, `${target.first_name} is restricted  by ${from.first_name}` + "for 5 mint")
    })
    return
  }
})

**Comment by NightfallAlicorn** [comment]
You'll have to program those methods manually. For example:

```js
var warnLog = {}

bot.on('replyCommand', (chat, date, from, messageId, text, command, commandData, target) => {
  // Type /warn reply target
  if (command === 'warn') {
    // Check if the chat id exists and an empty object ready for target users
    if (warnLog[chat.id] === undefined) {
      warnLog[chat.id] = {}
    }

    // Check if that user has been logged under warns for this chat before
    if (warnLog[chat.id][target.id] === undefined) {
      // Start with first warning if they hadn't
      warnLog[chat.id][target.id] = 1
    } else {
      // Increment the previous warning
      warnLog[chat.id][target.id]++
    }
    // Send text of number warnings the target user has had in this chat
    bot.sendText(chat.id, `${target.first_name} has been warned ${warnLog[chat.id][target.id]}`)
    return
  }
})
```

To keep track between restarts. You would need to us the `fs` module to store the data under a json format. Also to load it on the next server restart.

Just to note. You have an `index.js` which contains your script and `telegram-bot-nova.js` for the core communication handler with the server which doesn't need to be touched. All your stuff goes in `index.js`.

I hope this helps.

**Comment by dilshads** [comment]
can i have your telegram id ?

**Comment by dilshads** [comment]
Thanks man its working for me 

var warnLog = {}

bot.on('replyCommand', (chat, date, from, messageId, text, command, commandData, target) => {
  // Type /warn reply target
  if (command === 'warn') {
    // Check if the chat id exists and an empty object ready for target users
    if (warnLog[chat.id] === undefined) {
      warnLog[chat.id] = {}
    }

    // Check if that user has been logged under warns for this chat before
    if (warnLog[chat.id][target.id] === undefined) {
      // Start with first warning if they hadn't
      warnLog[chat.id][target.id] = 1
    } else {
      // Increment the previous warning
      warnLog[chat.id][target.id]++
    }
    // Send text of number warnings the target user has had in this chat
    bot.sendText(chat.id, `${target.first_name} has been warned ${warnLog[chat.id][target.id]}`)
  // defined number of max warning to get kicked
    if (warnLog[chat.id][target.id] === 3){
    bot.kickChatMember(chat.id, target.id, (error) => {

      if (error) {
        bot.sendText(chat.id, error.message)
        return
      }
      bot.sendText(chat.id, `${target.first_name} reached max number of warning and Kicked `)
    })
    return
}
  }
})

**Comment by dilshads** [comment]
can you please tell me how can i store it in file. 
i tired below code.

var warnLog = {}
var fs = require('fs');
fs.readFile('myjsonfile.json', 'utf8', function readFileCallback(err, data){
    if (err){
        console.log(err);
    } else {
    warnLog = JSON.parse(data); //now it an object
    json = JSON.stringify(warnLog); //convert it back to json
    fs.writeFile('myjsonfile.json', json, 'utf8', callback); // write it back 
}});

bot.on('replyCommand', (chat, date, from, messageId, text, command, commandData, target) => {
// Type /warn reply target
if (command === 'warn') {
// Check if the chat id exists and an empty object ready for target users
if (warnLog[chat.id] === undefined) {
warnLog[chat.id] = {}
}

// Check if that user has been logged under warns for this chat before
if (warnLog[chat.id][target.id] === undefined) {
  // Start with first warning if they hadn't
  warnLog[chat.id][target.id] = 1
  warnLog.push(warnLog[chat.id][target.id] =);
  var json = JSON.stringify(warnLog);
  fs.writeFile('myjsonfile.json', json, 'utf8', callback);
} else {
  // Increment the previous warning
  warnLog[chat.id][target.id]++
  warnLog.push(warnLog[chat.id][target.id]++);
  var json = JSON.stringify(warnLog);
  fs.writeFile('myjsonfile.json', json, 'utf8', callback);
}
// Send text of number warnings the target user has had in this chat
bot.sendText(chat.id, `${target.first_name} has been warned ${warnLog[chat.id][target.id]}`)
// defined number of max warning to get kicked
if (warnLog[chat.id][target.id] === 3){
bot.kickChatMember(chat.id, target.id, (error) => {

  if (error) {
    bot.sendText(chat.id, error.message)
    return
  }
  bot.sendText(chat.id, `${target.first_name} reached max number of warning and Kicked `)
})
return
}
}
})

**Comment by NightfallAlicorn** [comment]
Took me good few minutes but I've cleaned your code and got it working.

```js
'use strict'

// Module declares at the top
const fs = require('fs')
const TelegramBot = require('./telegram-bot-nova')

// Declare instance of a bot
var bot = new TelegramBot(YOUR_BOT_TOKEN)

var warnLog = {}

fs.readFile('myjsonfile.json', 'utf8', (error, data) => {
  if (error) {
    console.warn(error.message) // First time warning until file is created
  } else {
    warnLog = JSON.parse(data) // Read and parse data
  }
})

bot.on('replyCommand', (chat, date, from, messageId, text, command, commandData, target) => {
  // Type /warn reply target
  if (command === 'warn') {
    // Check if the chat id exists and an empty object ready for target users
    if (warnLog[chat.id] === undefined) {
      warnLog[chat.id] = {}
    }

    // Check if that user has been logged under warns for this chat before
    if (warnLog[chat.id][target.id] === undefined) {
      // Start with first warning if they hadn't
      warnLog[chat.id][target.id] = 1
    } else {
      // Increment the previous warning
      warnLog[chat.id][target.id]++
    }

    // Update log file
    fs.writeFile('myjsonfile.json', JSON.stringify(warnLog), 'utf8', (error) => {
      if (error) {
        console.warn(error.message)
      }
    })

    // Send text of number warnings the target user has had in this chat
    bot.sendText(chat.id, `${target.first_name} has been warned ${warnLog[chat.id][target.id]}`)

    // defined number of max warning to get kicked
    if (warnLog[chat.id][target.id] === 3) {
      bot.kickChatMember(chat.id, target.id, (error) => {
        if (error) {
          bot.sendText(chat.id, error.message)
          return
        }
        bot.sendText(chat.id, `${target.first_name} reached max number of warning and Kicked`)
      })
    }
  }
})
```

Just to note the issues section is for issues related to telegram-bot-nova. I'll provide examples on how to use the module but I don't want to help construct the whole code.

Also, I've noticed in the code you provided you may had confused arrays with objects. `warnLog[chat.id][target.id]` basically an object in an object and using push will only throw errors.

```
warnLog = {
  chat123: {
    user123: warnCount3
  }
}
```

This doesn't hold the absolute values but I just prefixed the numbers to help explain how it's structured.

To answer a previous question I rather prefer to keep my Telegram ID private.

Also another question. You'll have to use `setTimeout` for how long mutes will last and then make the bot disable the mute on the target user. Be warned that if the bot goes down while the target user is muted the user may not get unmuted by the bot.

Be sure to check https://stackoverflow.com if your still new to coding. Helped me a lot when I was a moderate coder of JavaScript.

**Comment by dilshads** [comment]
Thanks for support.
not an issue for telegram id..
you can contact me anytime ayaanx is my tg id...
